// APPLICATION CODES
const CONNETION_ERROR = "CONNETION_ERROR"
const CONNETION_SUCCESS = "CONNETION_SUCCESS"
const USER_LOGIN_SUCCESS = "USER LOGIN SUCCESS"
const USER_LOGIN_ERROR = "USER DOESN'T EXISTS"
const USER_SIGNUP_ERROR = "USER ALREADY EXISTS"
const USER_SIGNUP_SUCCESS = "ACCOUNT CREATED SUCCESSFULLY"

// MESSAGE CODES
const MESSAGE_CREATION_ERROR = "UNABLE TO CREATE MESSAGE"
const MESSAGE_CREATION_SUCCESS = "MESSAGE CREATED SUCCESSFULLY"

// SERVER CODES
const SERVER_ERROR = "SERVER ERROR"
const INVALID_URL = "INVALID URL"
const APPLICAITON_RUNNING = "APPLICAITON RUNNING"

// TOKEN CODES
const INVALID_TOKEN = "INVALID TOKEN."
const TOKEN_EXPIRED = "TOKEN EXPIRED."
const INVALID_USER_ACCESS = "INVALID USER ACCESS."

module.exports = {
    CONNETION_SUCCESS,
    CONNETION_ERROR,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_ERROR,
    USER_SIGNUP_ERROR,
    USER_SIGNUP_SUCCESS,
    SERVER_ERROR,
    INVALID_URL,
    APPLICAITON_RUNNING,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    INVALID_USER_ACCESS,
    MESSAGE_CREATION_SUCCESS,
    MESSAGE_CREATION_ERROR
}