const CONNETION_ERROR = "CONNETION_ERROR"
const CONNETION_SUCCESS = "CONNETION_SUCCESS"
const USER_LOGIN_SUCCESS = "USER LOGIN SUCCESS"
const USER_LOGIN_ERROR = "USER DOESN'T EXISTS"
const USER_SIGNUP_ERROR = "USER ALREADY EXISTS"
const USER_SIGNUP_SUCCESS = "ACCOUNT CREATED SUCCESSFULLY"
const SERVER_ERROR = "SERVER ERROR"

module.exports = {
    CONNETION_SUCCESS,
    CONNETION_ERROR,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_ERROR,
    USER_SIGNUP_ERROR,
    USER_SIGNUP_SUCCESS,
    SERVER_ERROR
}