const CONNETION_ERROR = "CONNETION_ERROR"
const CONNETION_SUCCESS = "CONNETION_SUCCESS"
const USER_LOGIN_SUCCSS = "USER LOGIN SUCCESS"
const USER_LOGIN_ERROR = "USER DOESN'T EXISTS"

module.exports = {
    CONNETION_SUCCESS,
    CONNETION_ERROR,
    USER_LOGIN_SUCCSS,
    USER_LOGIN_ERROR
}